version: '2'
services:
  jenkins:
    image: 'ims94/jenkins:latest'
    ports:
      - '8000:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    driver: local
